# Configuration for medium protein experiments
# Protein length: ~200 amino acids


protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
wandb_project: "GFN_Benchmark_Experiments"
run_name: "200A_Sequence_Conditional"
type: "medium"
device: "cuda"
arch: "MLP"