protein_seq: "MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*"
natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
wandb_project: "mRNA-CondGFN-Human-protein"  #"mRNA-CondGFN-small-tests"   #"mRNA-CondGFN-Human-protein"
run_name: "ACOT13-HomoSapiens-Protein"
device: "cuda"          
embedding_dim : 32
hidden_dim : 256
n_hidden : 2
tied : "store_true"

# 'INSR insulin receptor [ Homo sapiens (human) ]'
# MATGGRRGAAAAPLLVAVAALLLGAAGHLYPGEVCPGMDIRNNLTRLHELENCSVIEGHLQILLMFKTRPEDFRDLSFPKLIMITDYLLLFRVYGLESLKDLFPNLTV
# IRGSRLFFNYALVIFEMVHLKELGLYNLMNITRGSVRIEKNNELCYLATIDWSRILDSVEDNYIVLNKDDNEECGDICPGTAKGKTNCPATVINGQFVERCW
# THSHCQKVCPTICKSHGCTAEGLCCHSECLGNCSQPDDPTKCVACRNFYLDGRCVETCPPPYYHFQDWRC
# VNFSFCQDLHHKCKNSRRQGCHQYVIHNNKCIPECPSGYTMNSSNLLCTPCLGPCPKVCHLLEGEKTIDS
# VTSAQELRGCTVINGSLIINIRGGNNLAAELEANLGLIEEISGYLKIRRSYALVSLSFFRKLRLIRGETL
# EIGNYSFYALDNQNLRQLWDWSKHNLTITQGKLFFHYNPKLCLSEIHKMEEVSGTKGRQERNDIALKTNG
# DQASCENELLKFSYIRTSFDKILLRWEPYWPPDFRDLLGFMLFYKEAPYQNVTEFDGQDACGSNSWTVVD
# IDPPLRSNDPKSQNHPGWLMRGLKPWTQYAIFVKTLVTFSDERRTYGAKSDIIYVQTDATNPSVPLDPIS
# VSNSSSQIILKWKPPSDPNGNITHYLVFWERQAEDSELFELDYCLKGLKLPSRTWSPPFESEDSQKHNQS
# EYEDSAGECCSCPKTDSQILKELEESSFRKTFEDYLHNVVFVPRKTSSGTGAEDPRPSRKRRSLGDVGNV
# TVAVPTVAAFPNTSSTSVPTSPEEHRPFEKVVNKESLVISGLRHFTGYRIELQACNQDTPEERCSVAAYV
# SARTMPEAKADDIVGPVTHEIFENNVVHLMWQEPKEPNGLIVLYEVSYRRYGDEELHLCVSRKHFALERG
# CRLRGLSPGNYSVRIRATSLAGNGSWTEPTYFYVTDYLDVPSNIAKIIIGPLIFVFLFSVVIGSIYLFLR
# KRQPDGPLGPLYASSNPEYLSASDVFPCSVYVPDEWEVSREKITLLRELGQGSFGMVYEGNARDIIKGEA
# ETRVAVKTVNESASLRERIEFLNEASVMKGFTCHHVVRLLGVVSKGQPTLVVMELMAHGDLKSYLRSLRP
# EAENNPGRPPPTLQEMIQMAAEIADGMAYLNAKKFVHRDLAARNCMVAHDFTVKIGDFGMTRDIYETDYY
# RKGGKGLLPVRWMAPESLKDGVFTTSSDMWSFGVVLWEITSLAEQPYQGLSNEQVLKFVMDGGYLDQPDN
# CPERVTDLMRMCWQFNPKMRPTFLEIVNLLKDDLHPSFPEVSFFHSEENKAPESEELEMEFEDMENVPLD
# RSSHCQREEAGGRDGGSSLGFKRSYEEHIPYTHMNGGKKNGRILTLPRSNPS