protein_seq: 'MDSEM'
natural_mRNA_seq : 'AUGGACAGUGAGAUG'
wandb_project: "Test_mRNA_conditioning"
run_name: "Small_sequence_cdt"
type: "small"
device: "cuda"




# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"
# type: "small"
# device: "cuda"

# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
# type: "medium"
# device: "cuda"
# wandb_project: "Medium_sequences"
# run_name: "medium_run_MLP_config"
# arch : "MLP"


# protein_seq: 'MDSEM'
# natural_mRNA_seq : 'AUGGACAGUGAG'
# type: "small"
# device: "cuda"











# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"

# run_name: "Small_EHH_sequence_run"
# type: "small_EHH"

# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
# wandb_project: "mRNA_design_medium_141_seq"
# run_name: "Medium_sequence_run"
# type: "medium"
# device: "cuda"


# lenght 141 (medium run)
# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"

# lenght 547 (long run)
# protein_seq: "MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDPLKTPGRLDHGTRTAFIHHREQVWKRCINIWRDVGLFGVLNEIANSEEEVFEWVKTASGWALALCRWASSLHGSLFPHLSLRSEDLIAEFAQVTNWSSCCLRVFAWHPHTNKFAVALLDDSVRVYNASSTIVPSLKHRLQRNVASLAWKPLSASVLAVACQSCILIWTLDPTSLSTRPSSGCAQVLSHPGHTPVTSLAWAPSGGRLLSASPVDAAIRVWDVSTETCVPLPWFRGGGVTNLLWSPDGSKILATTPSAVFRVWEAQMWTCERWPTLSGRCQTGCWSPDGSRLLFTVLGEPLIYSLSFPERCGEGKGCVGGAKSATIVADLSETTIQTPDGEERLGGEAHSMVWDPSGERLAVLMKGKPRVQDGKPVILLFRTRNSPVFELLPCGIIQGEPGAQPQLITFHPSFNKGALLSVGWSTGRIAHIPLYFVNAQFPRFSPVLGRAQEPPAGGGGSIHDLPLFTETSPTSAPWDPLPGPPPVLPHSPHSHL*"
# natural_mRNA_seq : "AUGUGCUCUCUGGGGUUGUUCCCUCCUCCACCGCCUCGGGGUCAAGUCACCCUAUAUGAGCACAAUAACGAGCUGGUGACGGGCAGUAGCUAUGAGAGCCCGCCCCCCGACUUCCGGGGCCAGUGGAUCAAUCUUCCUGUCCUACAACUGACAAAGGAUCCCCUAAAGACCCCUGGAAGGCUGGACCAUGGCACAAGAACUGCCUUCAUCCAUCACCGGGAGCAAGUGUGGAAGAGAUGCAUCAACAUUUGGCGUGAUGUGGGCCUUUUUGGGGUGCUAAAUGAAAUUGCAAACUCAGAAGAAGAGGUGUUUGAGUGGGUGAAGACGGCAUCCGGCUGGGCCCUGGCACUCUGUCGAUGGGCCUCUUCCCUCCAUGGGUCCCUGUUCCCCCAUCUGUCUCUCAGGAGCGAAGAUCUGAUCGCUGAAUUUGCCCAAGUCACAAAUUGGUCCAGCUGCUGCUUGCGUGUCUUUGCAUGGCACCCCCACACCAACAAGUUUGCAGUGGCCCUGCUAGAUGACUCAGUCCGUGUGUAUAAUGCCAGCAGCACCAUAGUCCCCUCCCUGAAGCACCGGCUGCAGCGAAAUGUGGCGUCUCUGGCCUGGAAGCCCCUUAGUGCCUCUGUCUUGGCUGUGGCCUGCCAGAGCUGCAUUCUUAUCUGGACCCUGGACCCUACCUCCUUGUCUACCCGACCCUCUUCUGGCUGUGCCCAAGUGCUGUCUCACCCUGGGCAUACACCUGUUACCAGCUUGGCCUGGGCCCCCAGUGGGGGGCGGCUGCUCUCAGCUUCACCCGUGGAUGCUGCUAUCCGGGUAUGGGAUGUCUCAACAGAGACCUGUGUCCCCCUUCCCUGGUUCCGAGGAGGUGGGGUGACCAACCUGCUCUGGUCCCCAGACGGCAGCAAAAUCCUGGCUACCACUCCUUCAGCUGUCUUUCGAGUCUGGGAGGCCCAGAUGUGGACUUGUGAGAGGUGGCCUACUCUAUCAGGGCGCUGUCAGACUGGCUGCUGGAGCCCAGAUGGCAGCCGACUGCUGUUCACUGUAUUGGGAGAGCCACUGAUUUACUCCCUGUCUUUUCCAGAACGUUGUGGUGAGGGAAAGGGGUGCGUUGGAGGUGCAAAGUCAGCAACGAUUGUGGCAGAUCUGUCUGAGACAACAAUACAGACACCAGAUGGUGAGGAGAGGCUUGGGGGAGAGGCUCACUCCAUGGUCUGGGACCCCAGUGGGGAACGUCUGGCUGUGCUUAUGAAAGGAAAGCCAAGGGUACAGGAUGGUAAACCAGUCAUCCUCCUUUUUCGCACUCGAAACAGCCCUGUGUUUGAGCUCCUUCCCUGUGGCAUUAUCCAGGGGGAGCCAGGAGCCCAGCCCCAGCUCAUCACUUUCCAUCCUUCCUUCAACAAAGGGGCCCUGCUCAGUGUGGGCUGGUCCACAGGCCGAAUUGCCCACAUCCCGCUGUACUUUGUCAAUGCCCAGUUUCCACGUUUUAGCCCAGUGCUUGGGCGGGCCCAGGAACCCCCUGCUGGGGGUGGAGGCUCUAUUCAUGACCUGCCCCUCUUUACUGAGACAUCCCCAACCUCUGCCCCUUGGGACCCUCUCCCAGGGCCACCACCUGUUCUGCCCCACUCCCCACAUUCCCACCUCUAA"

# lenght 228 (medium run)
#'MGASARLLRAVIMGAPGSGKGTVSSRITTHFELKHLSSGDLLRDNMLRGTEIGVLAKAFIDQGKLIPDDVMTRLALHELKNLTQYSWLLDGFPRTLPQAEALDRAYQIDTVINLNVPFEVIKQRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEDQTKPVLEYYQKKGVLETFSGTETNKIWPYVYAFLQTKVPQRSQKASVTP*'
#AUGGGGGCGUCCGCGCGGCUGCUGCGAGCGGUGAUCAUGGGGGCCCCGGGCUCGGGCAAGGGCACCGUGUCGUCGCGCAUCACUACACACUUCGAGCUGAAGCACCUCUCCAGCGGGGACCUGCUCCGGGACAACAUGCUGCGGGGCACAGAAAUUGGCGUGUUAGCCAAGGCUUUCAUUGACCAAGGGAAACUCAUCCCAGAUGAUGUCAUGACUCGGCUGGCCCUUCAUGAGCUGAAAAAUCUCACCCAGUAUAGCUGGCUGUUGGAUGGUUUUCCAAGGACACUUCCACAGGCAGAAGCCCUAGAUAGAGCUUAUCAGAUCGACACAGUGAUUAACCUGAAUGUGCCCUUUGAGGUCAUUAAACAACGCCUUACUGCUCGCUGGAUUCAUCCCGCCAGUGGCCGAGUCUAUAACAUUGAAUUCAACCCUCCCAAAACUGUGGGCAUUGAUGACCUGACUGGGGAGCCUCUCAUUCAGCGUGAGGAUGAUAAACCAGAGACGGUUAUCAAGAGACUAAAGGCUUAUGAAGACCAAACAAAGCCAGUCCUGGAAUAUUACCAGAAAAAAGGGGUGCUGGAAACAUUCUCCGGAACAGAAACCAACAAGAUUUGGCCCUAUGUAUAUGCUUUCCUACAAACUAAAGUUCCACAAAGAAGCCAGAAAGCUUCAGUUACUCCAUGA

# lenght 75 (small run)
# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : "AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"









