# Configuration for medium protein experiments
# Protein length: ~200 amino acids


# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"



# Protein length: 120 amino acids

protein_seq : "MKLVRFLMKLSHETVTIELKNGTQVHGTITGVDVSMNTHLKAVKMTLKNREPVQLETLSIRGNNIRYFILPDSLPLDTLLVDVEPKVKSKKREAVAGRGRGRGRGRGRGRGRGRGGPRR*"
natural_mRNA_seq : "AUGAAGCUCGUGAGAUUUUUGAUGAAAUUGAGUCAUGAAACUGUAACCAUUGAAUUGAAGAACGGAACACAGGUCCAUGGAACAAUCACAGGUGUGGAUGUCAGCAUGAAUACACAUCUUAAAGCUGUGAAAAUGACCCUGAAGAACAGAGAACCUGUACAGCUGGAAACGCUGAGUAUUCGAGGAAAUAACAUUCGGUAUUUUAUUCUACCAGACAGUUUACCUCUGGAUACACUACUUGUGGAUGUUGAACCUAAGGUGAAAUCUAAGAAAAGGGAAGCUGUUGCAGGAAGAGGCAGAGGAAGAGGAAGAGGAAGAGGACGUGGCCGUGGCAGAGGAAGAGGGGGUCCUAGGCGAUAA"
wandb_project: "GFN_Benchmark_Experiments"
run_name: "120AA_Meidum_Sequence_Conditional"
type: "medium"
device: "cuda"
arch: "Transformer"

