# Configuration for large protein experiments
# Protein length: ~547 amino acids


# 228AA protein
protein_seq: 'MGASARLLRAVIMGAPGSGKGTVSSRITTHFELKHLSSGDLLRDNMLRGTEIGVLAKAFIDQGKLIPDDVMTRLALHELKNLTQYSWLLDGFPRTLPQAEALDRAYQIDTVINLNVPFEVIKQRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEDQTKPVLEYYQKKGVLETFSGTETNKIWPYVYAFLQTKVPQRSQKASVTP*'
natural_mRNA_seq: AUGGGGGCGUCCGCGCGGCUGCUGCGAGCGGUGAUCAUGGGGGCCCCGGGCUCGGGCAAGGGCACCGUGUCGUCGCGCAUCACUACACACUUCGAGCUGAAGCACCUCUCCAGCGGGGACCUGCUCCGGGACAACAUGCUGCGGGGCACAGAAAUUGGCGUGUUAGCCAAGGCUUUCAUUGACCAAGGGAAACUCAUCCCAGAUGAUGUCAUGACUCGGCUGGCCCUUCAUGAGCUGAAAAAUCUCACCCAGUAUAGCUGGCUGUUGGAUGGUUUUCCAAGGACACUUCCACAGGCAGAAGCCCUAGAUAGAGCUUAUCAGAUCGACACAGUGAUUAACCUGAAUGUGCCCUUUGAGGUCAUUAAACAACGCCUUACUGCUCGCUGGAUUCAUCCCGCCAGUGGCCGAGUCUAUAACAUUGAAUUCAACCCUCCCAAAACUGUGGGCAUUGAUGACCUGACUGGGGAGCCUCUCAUUCAGCGUGAGGAUGAUAAACCAGAGACGGUUAUCAAGAGACUAAAGGCUUAUGAAGACCAAACAAAGCCAGUCCUGGAAUAUUACCAGAAAAAAGGGGUGCUGGAAACAUUCUCCGGAACAGAAACCAACAAGAUUUGGCCCUAUGUAUAUGCUUUCCUACAAACUAAAGUUCCACAAAGAAGCCAGAAAGCUUCAGUUACUCCAUGA
wandb_project: "GFN_Benchmark_Eval_CL_Experiments"
run_name: "curriculum_eval_20250914"
type: "long"
device: "cuda"
arch: "Transformer"
























#'MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDPLKTPGRLDHGTRTAFIHHREQVWKRCINIWRDVGLFGVLNEIANSEEEVFEWVKTASGWALALCRWASSLHGSLFPHLSLRSEDLIAEFAQVTNWSSCCLRVFAWHPHTNKFAVALLDDSVRVYNASSTIVPSLKHRLQRNVASLAWKPLSASVLAVACQSCILIWTLDPTSLSTRPSSGCAQVLSHPGHTPVTSLAWAPSGGRLLSASPVDAAIRVWDVSTETCVPLPWFRGGGVTNLLWSPDGSKILATTPSAVFRVWEAQMWTCERWPTLSGRCQTGCWSPDGSRLLFTVLGEPLIYSLSFPERCGEGKGCVGGAKSATIVADLSETTIQTPDGEERLGGEAHSMVWDPSGERLAVLMKGKPRVQDGKPVILLFRTRNSPVFELLPCGIIQGEPGAQPQLITFHPSFNKGALLSVGWSTGRIAHIPLYFVNAQFPRFSPVLGRAQEPPAGGGGSIHDLPLFTETSPTSAPWDPLPGPPPVLPHSPHSHL*'
#'AUGUGCUCUCUGGGGUUGUUCCCUCCUCCACCGCCUCGGGGUCAAGUCACCCUAUAUGAGCACAAUAACGAGCUGGUGACGGGCAGUAGCUAUGAGAGCCCGCCCCCCGACUUCCGGGGCCAGUGGAUCAAUCUUCCUGUCCUACAACUGACAAAGGAUCCCCUAAAGACCCCUGGAAGGCUGGACCAUGGCACAAGAACUGCCUUCAUCCAUCACCGGGAGCAAGUGUGGAAGAGAUGCAUCAACAUUUGGCGUGAUGUGGGCCUUUUUGGGGUGCUAAAUGAAAUUGCAAACUCAGAAGAAGAGGUGUUUGAGUGGGUGAAGACGGCAUCCGGCUGGGCCCUGGCACUCUGUCGAUGGGCCUCUUCCCUCCAUGGGUCCCUGUUCCCCCAUCUGUCUCUCAGGAGCGAAGAUCUGAUCGCUGAAUUUGCCCAAGUCACAAAUUGGUCCAGCUGCUGCUUGCGUGUCUUUGCAUGGCACCCCCACACCAACAAGUUUGCAGUGGCCCUGCUAGAUGACUCAGUCCGUGUGUAUAAUGCCAGCAGCACCAUAGUCCCCUCCCUGAAGCACCGGCUGCAGCGAAAUGUGGCGUCUCUGGCCUGGAAGCCCCUUAGUGCCUCUGUCUUGGCUGUGGCCUGCCAGAGCUGCAUUCUUAUCUGGACCCUGGACCCUACCUCCUUGUCUACCCGACCCUCUUCUGGCUGUGCCCAAGUGCUGUCUCACCCUGGGCAUACACCUGUUACCAGCUUGGCCUGGGCCCCCAGUGGGGGGCGGCUGCUCUCAGCUUCACCCGUGGAUGCUGCUAUCCGGGUAUGGGAUGUCUCAACAGAGACCUGUGUCCCCCUUCCCUGGUUCCGAGGAGGUGGGGUGACCAACCUGCUCUGGUCCCCAGACGGCAGCAAAAUCCUGGCUACCACUCCUUCAGCUGUCUUUCGAGUCUGGGAGGCCCAGAUGUGGACUUGUGAGAGGUGGCCUACUCUAUCAGGGCGCUGUCAGACUGGCUGCUGGAGCCCAGAUGGCAGCCGACUGCUGUUCACUGUAUUGGGAGAGCCACUGAUUUACUCCCUGUCUUUUCCAGAACGUUGUGGUGAGGGAAAGGGGUGCGUUGGAGGUGCAAAGUCAGCAACGAUUGUGGCAGAUCUGUCUGAGACAACAAUACAGACACCAGAUGGUGAGGAGAGGCUUGGGGGAGAGGCUCACUCCAUGGUCUGGGACCCCAGUGGGGAACGUCUGGCUGUGCUUAUGAAAGGAAAGCCAAGGGUACAGGAUGGUAAACCAGUCAUCCUCCUUUUUCGCACUCGAAACAGCCCUGUGUUUGAGCUCCUUCCCUGUGGCAUUAUCCAGGGGGAGCCAGGAGCCCAGCCCCAGCUCAUCACUUUCCAUCCUUCCUUCAACAAAGGGGCCCUGCUCAGUGUGGGCUGGUCCACAGGCCGAAUUGCCCACAUCCCGCUGUACUUUGUCAAUGCCCAGUUUCCACGUUUUAGCCCAGUGCUUGGGCGGGCCCAGGAACCCCCUGCUGGGGGUGGAGGCUCUAUUCAUGACCUGCCCCUCUUUACUGAGACAUCCCCAACCUCUGCCCCUUGGGACCCUCUCCCAGGGCCACCACCUGUUCUGCCCCACUCCCCACAUUCCCACCUCUAA'
