# Configuration for small protein experiments
# Protein length: ~33 amino acids

protein_seq: "MINTQDSSILPLSNCPQLQCCRHIVPGPLWCS*"
natural_mRNA_seq: "AUGAUAAACACCCAGGACAGUAGUAUUUUGCCUUUGAGUAACUGUCCCCAGCUCCAGUGCUGCAGGCACAUUGUUCCAGGGCCUCUGUGGUGCUCCUAA"
wandb_project: "BASELINE"
run_name: "Conditional_GFN"
type: "small"
device: "cuda"
arch: "Transformer"





