# Configuration for small protein experiments
# Protein length: ~75 amino acids

# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq: 'AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA'



protein_seq: "MINTQDSSILPLSNCPQLQCCRHIVPGPLWCS*"
natural_mRNA_seq: "AUGAUAAACACCCAGGACAGUAGUAUUUUGCCUUUGAGUAACUGUCCCCAGCUCCAGUGCUGCAGGCACAUUGUUCCAGGGCCUCUGUGGUGCUCCUAA"
wandb_project: "BASELINE_Experiments"
run_name: "Conditional_Small_Sequence_32AA"
type: "small"
device: "cuda"
arch: "Transformer"





