protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
wandb_project: "mRNA_design_141_seq"
run_name: "NM_018473-HomoSapiens-Protein-best-run"
device: "cuda"











# lenght 141 (first one)
# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"


# lenght 547
#"MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDPLKTPGRLDHGTRTAFIHHREQVWKRCINIWRDVGLFGVLNEIANSEEEVFEWVKTASGWALALCRWASSLHGSLFPHLSLRSEDLIAEFAQVTNWSSCCLRVFAWHPHTNKFAVALLDDSVRVYNASSTIVPSLKHRLQRNVASLAWKPLSASVLAVACQSCILIWTLDPTSLSTRPSSGCAQVLSHPGHTPVTSLAWAPSGGRLLSASPVDAAIRVWDVSTETCVPLPWFRGGGVTNLLWSPDGSKILATTPSAVFRVWEAQMWTCERWPTLSGRCQTGCWSPDGSRLLFTVLGEPLIYSLSFPERCGEGKGCVGGAKSATIVADLSETTIQTPDGEERLGGEAHSMVWDPSGERLAVLMKGKPRVQDGKPVILLFRTRNSPVFELLPCGIIQGEPGAQPQLITFHPSFNKGALLSVGWSTGRIAHIPLYFVNAQFPRFSPVLGRAQEPPAGGGGSIHDLPLFTETSPTSAPWDPLPGPPPVLPHSPHSHL*"
#"AUGUGCUCUCUGGGGUUGUUCCCUCCUCCACCGCCUCGGGGUCAAGUCACCCUAUAUGAGCACAAUAACGAGCUGGUGACGGGCAGUAGCUAUGAGAGCCCGCCCCCCGACUUCCGGGGCCAGUGGAUCAAUCUUCCUGUCCUACAACUGACAAAGGAUCCCCUAAAGACCCCUGGAAGGCUGGACCAUGGCACAAGAACUGCCUUCAUCCAUCACCGGGAGCAAGUGUGGAAGAGAUGCAUCAACAUUUGGCGUGAUGUGGGCCUUUUUGGGGUGCUAAAUGAAAUUGCAAACUCAGAAGAAGAGGUGUUUGAGUGGGUGAAGACGGCAUCCGGCUGGGCCCUGGCACUCUGUCGAUGGGCCUCUUCCCUCCAUGGGUCCCUGUUCCCCCAUCUGUCUCUCAGGAGCGAAGAUCUGAUCGCUGAAUUUGCCCAAGUCACAAAUUGGUCCAGCUGCUGCUUGCGUGUCUUUGCAUGGCACCCCCACACCAACAAGUUUGCAGUGGCCCUGCUAGAUGACUCAGUCCGUGUGUAUAAUGCCAGCAGCACCAUAGUCCCCUCCCUGAAGCACCGGCUGCAGCGAAAUGUGGCGUCUCUGGCCUGGAAGCCCCUUAGUGCCUCUGUCUUGGCUGUGGCCUGCCAGAGCUGCAUUCUUAUCUGGACCCUGGACCCUACCUCCUUGUCUACCCGACCCUCUUCUGGCUGUGCCCAAGUGCUGUCUCACCCUGGGCAUACACCUGUUACCAGCUUGGCCUGGGCCCCCAGUGGGGGGCGGCUGCUCUCAGCUUCACCCGUGGAUGCUGCUAUCCGGGUAUGGGAUGUCUCAACAGAGACCUGUGUCCCCCUUCCCUGGUUCCGAGGAGGUGGGGUGACCAACCUGCUCUGGUCCCCAGACGGCAGCAAAAUCCUGGCUACCACUCCUUCAGCUGUCUUUCGAGUCUGGGAGGCCCAGAUGUGGACUUGUGAGAGGUGGCCUACUCUAUCAGGGCGCUGUCAGACUGGCUGCUGGAGCCCAGAUGGCAGCCGACUGCUGUUCACUGUAUUGGGAGAGCCACUGAUUUACUCCCUGUCUUUUCCAGAACGUUGUGGUGAGGGAAAGGGGUGCGUUGGAGGUGCAAAGUCAGCAACGAUUGUGGCAGAUCUGUCUGAGACAACAAUACAGACACCAGAUGGUGAGGAGAGGCUUGGGGGAGAGGCUCACUCCAUGGUCUGGGACCCCAGUGGGGAACGUCUGGCUGUGCUUAUGAAAGGAAAGCCAAGGGUACAGGAUGGUAAACCAGUCAUCCUCCUUUUUCGCACUCGAAACAGCCCUGUGUUUGAGCUCCUUCCCUGUGGCAUUAUCCAGGGGGAGCCAGGAGCCCAGCCCCAGCUCAUCACUUUCCAUCCUUCCUUCAACAAAGGGGCCCUGCUCAGUGUGGGCUGGUCCACAGGCCGAAUUGCCCACAUCCCGCUGUACUUUGUCAAUGCCCAGUUUCCACGUUUUAGCCCAGUGCUUGGGCGGGCCCAGGAACCCCCUGCUGGGGGUGGAGGCUCUAUUCAUGACCUGCCCCUCUUUACUGAGACAUCCCCAACCUCUGCCCCUUGGGACCCUCUCCCAGGGCCACCACCUGUUCUGCCCCACUCCCCACAUUCCCACCUCUAA"

# lenght 228
#'MGASARLLRAVIMGAPGSGKGTVSSRITTHFELKHLSSGDLLRDNMLRGTEIGVLAKAFIDQGKLIPDDVMTRLALHELKNLTQYSWLLDGFPRTLPQAEALDRAYQIDTVINLNVPFEVIKQRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEDQTKPVLEYYQKKGVLETFSGTETNKIWPYVYAFLQTKVPQRSQKASVTP*'
#AUGGGGGCGUCCGCGCGGCUGCUGCGAGCGGUGAUCAUGGGGGCCCCGGGCUCGGGCAAGGGCACCGUGUCGUCGCGCAUCACUACACACUUCGAGCUGAAGCACCUCUCCAGCGGGGACCUGCUCCGGGACAACAUGCUGCGGGGCACAGAAAUUGGCGUGUUAGCCAAGGCUUUCAUUGACCAAGGGAAACUCAUCCCAGAUGAUGUCAUGACUCGGCUGGCCCUUCAUGAGCUGAAAAAUCUCACCCAGUAUAGCUGGCUGUUGGAUGGUUUUCCAAGGACACUUCCACAGGCAGAAGCCCUAGAUAGAGCUUAUCAGAUCGACACAGUGAUUAACCUGAAUGUGCCCUUUGAGGUCAUUAAACAACGCCUUACUGCUCGCUGGAUUCAUCCCGCCAGUGGCCGAGUCUAUAACAUUGAAUUCAACCCUCCCAAAACUGUGGGCAUUGAUGACCUGACUGGGGAGCCUCUCAUUCAGCGUGAGGAUGAUAAACCAGAGACGGUUAUCAAGAGACUAAAGGCUUAUGAAGACCAAACAAAGCCAGUCCUGGAAUAUUACCAGAAAAAAGGGGUGCUGGAAACAUUCUCCGGAACAGAAACCAACAAGAUUUGGCCCUAUGUAUAUGCUUUCCUACAAACUAAAGUUCCACAAAGAAGCCAGAAAGCUUCAGUUACUCCAUGA

# lenght 75 (seccond one)
# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : "AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"









