# protein_seq: 'AACAAGAAGGAATAACAGTGGAGTGTTAAGGCGGGATGGCATGCTATAAA'
# natural_mRNA_seq : 'AUGGCGGCCUGCAUUGCAGCGGGGCACUGGGCUGCAAUGGGCCUAGGCCGGAGUUUCCAAGCCGCCAGGACUCUGCUCCCCCCGCCGGCCUCUAUCGCCUGCAGGGUCCACGCGGGGCCUGUCCGGCAGCAGAGCACUGGGCCUUCCGAGCCCGGUGCGUUCCAACCGCCGCCGAAACCGGUCAUCGUGGACAAGCACCGCCCCGUGGAACCGGAACGCAGGUUCUUGAGUCCUGAAUUCAUUCCUCGAAGGGGAAGAACAGAUCCUCUGAAAUUUCAAAUAGAAAGAAAAGAUAUGUUAGAAAGGAGAAAAGUACUCCACAUUCCAGAGUUCUAUGUUGGAAGUAUUCUUCGUGUUACUACAGCUGACCCAUAUGCCAGUGGAAAAAUCAGCCAGUUUCUGGGGAUUUGCAUUCAGAGAUCAGGAAGAGGACUUGGAGCUACUUUCAUCCUUAGGAAUGUUAUCGAAGGACAAGGUGUCGAGAUUUGCUUUGAACUUUAUAAUCCUCGGGUCCAGGAGAUUCAGGUGGUCAAAUUAGAGAAACGGCUGGAUGAUAGCUUGCUAUACUUACGAGAUGCCCUUCCUGAAUAUAGCACUUUUGAUGUGAAUAUGAAGCCAGUAGUACAAGAGCCUAACCAAAAAGUUCCUGUUAAUGAGCUGAAAGUAAAAAUGAAGCCUAAGCCCUGGUCUAAACGCUGGGAACGUCCAAAUUUUAAUAUUAAAGGAAUCAGAUUUGAUCUUUGUUUAACUGAACAGCAAAUGAAAGAAGCUCAGAAGUGGAAUCAGCCAUGGCUUGAAUUUGAUAUGAUGAGGGAAUAUGAUACUUCAAAAAUUGAAGCUGCAAUAUGGAAGGAAAUUGAAGCGUCGAAAAGGUCUUGA'


# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"


# protein_seq: 'AACAAGAAGGAATAACAGTGGAGTGTTAAGGCGGGATGGCATGCTATAAA'
# natural_mRNA_seq : 'AUGGCGGCCUGCAUUGCAGCGGGGCACUGGGCUGCAAUGGGCCUAGGCCGGAGUUUCCAAGCCGCCAGGACUCUGCUCCCCCCGCCGGCCUCUAUCGCCUGCAGGGUCCACGCGGGGCCUGUCCGGCAGCAGAGCACUGGGCCUUCCGAGCCCGGUGCGUUCCAACCGCCGCCGAAACCGGUCAUCGUGGACAAGCACCGCCCCGUGGAACCGGAACGCAGGUUCUUGAGUCCUGAAUUCAUUCCUCGAAGGGGAAGAACAGAUCCUCUGAAAUUUCAAAUAGAAAGAAAAGAUAUGUUAGAAAGGAGAAAAGUACUCCACAUUCCAGAGUUCUAUGUUGGAAGUAUUCUUCGUGUUACUACAGCUGACCCAUAUGCCAGUGGAAAAAUCAGCCAGUUUCUGGGGAUUUGCAUUCAGAGAUCAGGAAGAGGACUUGGAGCUACUUUCAUCCUUAGGAAUGUUAUCGAAGGACAAGGUGUCGAGAUUUGCUUUGAACUUUAUAAUCCUCGGGUCCAGGAGAUUCAGGUGGUCAAAUUAGAGAAACGGCUGGAUGAUAGCUUGCUAUACUUACGAGAUGCCCUUCCUGAAUAUAGCACUUUUGAUGUGAAUAUGAAGCCAGUAGUACAAGAGCCUAACCAAAAAGUUCCUGUUAAUGAGCUGAAAGUAAAAAUGAAGCCUAAGCCCUGGUCUAAACGCUGGGAACGUCCAAAUUUUAAUAUUAAAGGAAUCAGAUUUGAUCUUUGUUUAACUGAACAGCAAAUGAAAGAAGCUCAGAAGUGGAAUCAGCCAUGGCUUGAAUUUGAUAUGAUGAGGGAAUAUGAUACUUCAAAAAUUGAAGCUGCAAUAUGGAAGGAAAUUGAAGCGUCGAAAAGGUCUUGA'


protein_seq: 'MDSEM'
natural_mRNA_seq : 'AUGGACAGUGAG'
wandb_project: "My_experiments"
run_name: "TEST"
type: "small"
arch : "MLP"
device: "cuda"






# run_name: "Medium_seq_Conditional_test"
# type: "medium"
# arch : "MLP"
# device: "cuda"






























# protein_seq: 'MDSEM'
# natural_mRNA_seq : 'AUGGACAGUGAG'




# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"
# wandb_project: "GFN_Organized_Experiments_With_Analysis"
# run_name: "Small_seq_Unconditional_GFN_MLP"
# type: "small"
# arch : "MLP"
# device: "cuda"




























# protein_seq: 'MDSEM'
# natural_mRNA_seq : 'AUGGACAGUGAG'

# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"
# wandb_project: "GFN_Simple_Reward_Cond"
# run_name: "Conditional_Small_seq_Simple_Reward" # Unconditional_Small_seq_Simple_Reward
# type: "small"
# device: "cuda"
# arch : "MLP"


# wandb_project: "GFN_Conditional_GFN_protein_conditioning"
# run_name: "Small_seq_Conditional_GFN_MLP"




# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
# wandb_project: "GFN_Comparison_Cond_vs_Uncond"
# run_name: "Medium_seq_Unconditional_GFN"
# type: "medium"
# device: "cuda"


# protein_seq : 'MGASARLLRAVIMGAPGSGKGTVSSRITTHFELKHLSSGDLLRDNMLRGTEIGVLAKAFIDQGKLIPDDVMTRLALHELKNLTQYSWLLDGFPRTLPQAEALDRAYQIDTVINLNVPFEVIKQRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEDQTKPVLEYYQKKGVLETFSGTETNKIWPYVYAFLQTKVPQRSQKASVTP*'
# natural_mRNA_seq : 'AUGGGGGCGUCCGCGCGGCUGCUGCGAGCGGUGAUCAUGGGGGCCCCGGGCUCGGGCAAGGGCACCGUGUCGUCGCGCAUCACUACACACUUCGAGCUGAAGCACCUCUCCAGCGGGGACCUGCUCCGGGACAACAUGCUGCGGGGCACAGAAAUUGGCGUGUUAGCCAAGGCUUUCAUUGACCAAGGGAAACUCAUCCCAGAUGAUGUCAUGACUCGGCUGGCCCUUCAUGAGCUGAAAAAUCUCACCCAGUAUAGCUGGCUGUUGGAUGGUUUUCCAAGGACACUUCCACAGGCAGAAGCCCUAGAUAGAGCUUAUCAGAUCGACACAGUGAUUAACCUGAAUGUGCCCUUUGAGGUCAUUAAACAACGCCUUACUGCUCGCUGGAUUCAUCCCGCCAGUGGCCGAGUCUAUAACAUUGAAUUCAACCCUCCCAAAACUGUGGGCAUUGAUGACCUGACUGGGGAGCCUCUCAUUCAGCGUGAGGAUGAUAAACCAGAGACGGUUAUCAAGAGACUAAAGGCUUAUGAAGACCAAACAAAGCCAGUCCUGGAAUAUUACCAGAAAAAAGGGGUGCUGGAAACAUUCUCCGGAACAGAAACCAACAAGAUUUGGCCCUAUGUAUAUGCUUUCCUACAAACUAAAGUUCCACAAAGAAGCCAGAAAGCUUCAGUUACUCCAUGA'
# wandb_project: "GFN_Comparison_Cond_vs_Uncond"
# run_name: "Long_seq_Unconditional_GFN"
# type: "long"
# device: "cuda"











# wandb_project: "Test_GFN_with_conditioning"
# run_name: "Long_sequence_run"
# wandb_project: "Medium_sequences"
# run_name: "long_run_MLP_config"
# device: "cuda"






















# wandb_project: "Test_GFN_with_conditioning"
# run_name: "Medium_sequence_run"
# # type: "small"
# device: "cuda"

# protein_seq : 'MGASARLLRAVIMGAPGSGKGTVSSRITTHFELKHLSSGDLLRDNMLRGTEIGVLAKAFIDQGKLIPDDVMTRLALHELKNLTQYSWLLDGFPRTLPQAEALDRAYQIDTVINLNVPFEVIKQRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEDQTKPVLEYYQKKGVLETFSGTETNKIWPYVYAFLQTKVPQRSQKASVTP*'
# natural_mRNA_seq : 'AUGGGGGCGUCCGCGCGGCUGCUGCGAGCGGUGAUCAUGGGGGCCCCGGGCUCGGGCAAGGGCACCGUGUCGUCGCGCAUCACUACACACUUCGAGCUGAAGCACCUCUCCAGCGGGGACCUGCUCCGGGACAACAUGCUGCGGGGCACAGAAAUUGGCGUGUUAGCCAAGGCUUUCAUUGACCAAGGGAAACUCAUCCCAGAUGAUGUCAUGACUCGGCUGGCCCUUCAUGAGCUGAAAAAUCUCACCCAGUAUAGCUGGCUGUUGGAUGGUUUUCCAAGGACACUUCCACAGGCAGAAGCCCUAGAUAGAGCUUAUCAGAUCGACACAGUGAUUAACCUGAAUGUGCCCUUUGAGGUCAUUAAACAACGCCUUACUGCUCGCUGGAUUCAUCCCGCCAGUGGCCGAGUCUAUAACAUUGAAUUCAACCCUCCCAAAACUGUGGGCAUUGAUGACCUGACUGGGGAGCCUCUCAUUCAGCGUGAGGAUGAUAAACCAGAGACGGUUAUCAAGAGACUAAAGGCUUAUGAAGACCAAACAAAGCCAGUCCUGGAAUAUUACCAGAAAAAAGGGGUGCUGGAAACAUUCUCCGGAACAGAAACCAACAAGAUUUGGCCCUAUGUAUAUGCUUUCCUACAAACUAAAGUUCCACAAAGAAGCCAGAAAGCUUCAGUUACUCCAUGA'
# type: "long"
# # wandb_project: "Test_GFN_with_conditioning"
# # run_name: "Long_sequence_run"
# wandb_project: "Medium_sequences"
# run_name: "long_run_MLP_config"
# device: "cuda"

# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
# type: "medium"
# device: "cuda"
# wandb_project: "Medium_sequences"
# run_name: "medium_run_MLP_config"
# arch : "MLP"

# protein_seq: 'MDSEM'
# natural_mRNA_seq : 'AUGGACAGUGAG'
# type: "small"
# device: "cuda"











# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"

# run_name: "Small_EHH_sequence_run"
# type: "small_EHH"

# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
# wandb_project: "mRNA_design_medium_141_seq"
# run_name: "Medium_sequence_run"
# type: "medium"
# device: "cuda"


# lenght 141 (medium run)
# protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
# natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"

# lenght 547 (long run)
# protein_seq: "MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDPLKTPGRLDHGTRTAFIHHREQVWKRCINIWRDVGLFGVLNEIANSEEEVFEWVKTASGWALALCRWASSLHGSLFPHLSLRSEDLIAEFAQVTNWSSCCLRVFAWHPHTNKFAVALLDDSVRVYNASSTIVPSLKHRLQRNVASLAWKPLSASVLAVACQSCILIWTLDPTSLSTRPSSGCAQVLSHPGHTPVTSLAWAPSGGRLLSASPVDAAIRVWDVSTETCVPLPWFRGGGVTNLLWSPDGSKILATTPSAVFRVWEAQMWTCERWPTLSGRCQTGCWSPDGSRLLFTVLGEPLIYSLSFPERCGEGKGCVGGAKSATIVADLSETTIQTPDGEERLGGEAHSMVWDPSGERLAVLMKGKPRVQDGKPVILLFRTRNSPVFELLPCGIIQGEPGAQPQLITFHPSFNKGALLSVGWSTGRIAHIPLYFVNAQFPRFSPVLGRAQEPPAGGGGSIHDLPLFTETSPTSAPWDPLPGPPPVLPHSPHSHL*"
# natural_mRNA_seq : "AUGUGCUCUCUGGGGUUGUUCCCUCCUCCACCGCCUCGGGGUCAAGUCACCCUAUAUGAGCACAAUAACGAGCUGGUGACGGGCAGUAGCUAUGAGAGCCCGCCCCCCGACUUCCGGGGCCAGUGGAUCAAUCUUCCUGUCCUACAACUGACAAAGGAUCCCCUAAAGACCCCUGGAAGGCUGGACCAUGGCACAAGAACUGCCUUCAUCCAUCACCGGGAGCAAGUGUGGAAGAGAUGCAUCAACAUUUGGCGUGAUGUGGGCCUUUUUGGGGUGCUAAAUGAAAUUGCAAACUCAGAAGAAGAGGUGUUUGAGUGGGUGAAGACGGCAUCCGGCUGGGCCCUGGCACUCUGUCGAUGGGCCUCUUCCCUCCAUGGGUCCCUGUUCCCCCAUCUGUCUCUCAGGAGCGAAGAUCUGAUCGCUGAAUUUGCCCAAGUCACAAAUUGGUCCAGCUGCUGCUUGCGUGUCUUUGCAUGGCACCCCCACACCAACAAGUUUGCAGUGGCCCUGCUAGAUGACUCAGUCCGUGUGUAUAAUGCCAGCAGCACCAUAGUCCCCUCCCUGAAGCACCGGCUGCAGCGAAAUGUGGCGUCUCUGGCCUGGAAGCCCCUUAGUGCCUCUGUCUUGGCUGUGGCCUGCCAGAGCUGCAUUCUUAUCUGGACCCUGGACCCUACCUCCUUGUCUACCCGACCCUCUUCUGGCUGUGCCCAAGUGCUGUCUCACCCUGGGCAUACACCUGUUACCAGCUUGGCCUGGGCCCCCAGUGGGGGGCGGCUGCUCUCAGCUUCACCCGUGGAUGCUGCUAUCCGGGUAUGGGAUGUCUCAACAGAGACCUGUGUCCCCCUUCCCUGGUUCCGAGGAGGUGGGGUGACCAACCUGCUCUGGUCCCCAGACGGCAGCAAAAUCCUGGCUACCACUCCUUCAGCUGUCUUUCGAGUCUGGGAGGCCCAGAUGUGGACUUGUGAGAGGUGGCCUACUCUAUCAGGGCGCUGUCAGACUGGCUGCUGGAGCCCAGAUGGCAGCCGACUGCUGUUCACUGUAUUGGGAGAGCCACUGAUUUACUCCCUGUCUUUUCCAGAACGUUGUGGUGAGGGAAAGGGGUGCGUUGGAGGUGCAAAGUCAGCAACGAUUGUGGCAGAUCUGUCUGAGACAACAAUACAGACACCAGAUGGUGAGGAGAGGCUUGGGGGAGAGGCUCACUCCAUGGUCUGGGACCCCAGUGGGGAACGUCUGGCUGUGCUUAUGAAAGGAAAGCCAAGGGUACAGGAUGGUAAACCAGUCAUCCUCCUUUUUCGCACUCGAAACAGCCCUGUGUUUGAGCUCCUUCCCUGUGGCAUUAUCCAGGGGGAGCCAGGAGCCCAGCCCCAGCUCAUCACUUUCCAUCCUUCCUUCAACAAAGGGGCCCUGCUCAGUGUGGGCUGGUCCACAGGCCGAAUUGCCCACAUCCCGCUGUACUUUGUCAAUGCCCAGUUUCCACGUUUUAGCCCAGUGCUUGGGCGGGCCCAGGAACCCCCUGCUGGGGGUGGAGGCUCUAUUCAUGACCUGCCCCUCUUUACUGAGACAUCCCCAACCUCUGCCCCUUGGGACCCUCUCCCAGGGCCACCACCUGUUCUGCCCCACUCCCCACAUUCCCACCUCUAA"

# lenght 228 (medium run)
#'MGASARLLRAVIMGAPGSGKGTVSSRITTHFELKHLSSGDLLRDNMLRGTEIGVLAKAFIDQGKLIPDDVMTRLALHELKNLTQYSWLLDGFPRTLPQAEALDRAYQIDTVINLNVPFEVIKQRLTARWIHPASGRVYNIEFNPPKTVGIDDLTGEPLIQREDDKPETVIKRLKAYEDQTKPVLEYYQKKGVLETFSGTETNKIWPYVYAFLQTKVPQRSQKASVTP*'
#AUGGGGGCGUCCGCGCGGCUGCUGCGAGCGGUGAUCAUGGGGGCCCCGGGCUCGGGCAAGGGCACCGUGUCGUCGCGCAUCACUACACACUUCGAGCUGAAGCACCUCUCCAGCGGGGACCUGCUCCGGGACAACAUGCUGCGGGGCACAGAAAUUGGCGUGUUAGCCAAGGCUUUCAUUGACCAAGGGAAACUCAUCCCAGAUGAUGUCAUGACUCGGCUGGCCCUUCAUGAGCUGAAAAAUCUCACCCAGUAUAGCUGGCUGUUGGAUGGUUUUCCAAGGACACUUCCACAGGCAGAAGCCCUAGAUAGAGCUUAUCAGAUCGACACAGUGAUUAACCUGAAUGUGCCCUUUGAGGUCAUUAAACAACGCCUUACUGCUCGCUGGAUUCAUCCCGCCAGUGGCCGAGUCUAUAACAUUGAAUUCAACCCUCCCAAAACUGUGGGCAUUGAUGACCUGACUGGGGAGCCUCUCAUUCAGCGUGAGGAUGAUAAACCAGAGACGGUUAUCAAGAGACUAAAGGCUUAUGAAGACCAAACAAAGCCAGUCCUGGAAUAUUACCAGAAAAAAGGGGUGCUGGAAACAUUCUCCGGAACAGAAACCAACAAGAUUUGGCCCUAUGUAUAUGCUUUCCUACAAACUAAAGUUCCACAAAGAAGCCAGAAAGCUUCAGUUACUCCAUGA





# lenght 75 (small run)
# protein_seq: 'MDSEVQRDGRILDLIDDAWREDKLPYEDVAIPLNELPEPEQDNGGTTESVKEQEMKWTDLALQYLHENVPPIGN*'
# natural_mRNA_seq : "AUGGACAGUGAGGUUCAGAGAGAUGGAAGGAUCUUGGAUUUGAUUGAUGAUGCUUGGCGAGAAGACAAGCUGCCUUAUGAGGAUGUCGCAAUACCACUGAAUGAGCUUCCUGAACCUGAACAAGACAAUGGUGGCACCACAGAAUCUGUCAAAGAACAAGAAAUGAAGUGGACAGACUUAGCCUUACAGUACCUCCAUGAGAAUGUUCCCCCCAUUGGAAACUGA"









