# Protein length: 120 amino acids

protein_seq : "MKLVRFLMKLSHETVTIELKNGTQVHGTITGVDVSMNTHLKAVKMTLKNREPVQLETLSIRGNNIRYFILPDSLPLDTLLVDVEPKVKSKKREAVAGRGRGRGRGRGRGRGRGRGGPRR*"
natural_mRNA_seq : "AUGAAGCUCGUGAGAUUUUUGAUGAAAUUGAGUCAUGAAACUGUAACCAUUGAAUUGAAGAACGGAACACAGGUCCAUGGAACAAUCACAGGUGUGGAUGUCAGCAUGAAUACACAUCUUAAAGCUGUGAAAAUGACCCUGAAGAACAGAGAACCUGUACAGCUGGAAACGCUGAGUAUUCGAGGAAAUAACAUUCGGUAUUUUAUUCUACCAGACAGUUUACCUCUGGAUACACUACUUGUGGAUGUUGAACCUAAGGUGAAAUCUAAGAAAAGGGAAGCUGUUGCAGGAAGAGGCAGAGGAAGAGGAAGAGGAAGAGGACGUGGCCGUGGCAGAGGAAGAGGGGGUCCUAGGCGAUAA"
wandb_project: "CAGFN_Experiments"
run_name: "120AA_Medium_Sequence_Conditional"
type: "medium"
device: "cuda"
arch: "Transformer"

