# Protein length: ~33 amino acids


protein_seq: "MINTQDSSILPLSNCPQLQCCRHIVPGPLWCS*"
natural_mRNA_seq: "AUGAUAAACACCCAGGACAGUAGUAUUUUGCCUUUGAGUAACUGUCCCCAGCUCCAGUGCUGCAGGCACAUUGUUCCAGGGCCUCUGUGGUGCUCCUAA"
wandb_project: "My_experiments"
run_name: "TEST"
type: "small"
arch : "Transformer"
device: "cuda"



