protein_seq: 'MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*'
natural_mRNA_seq : "AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA"
wandb_project: "mRNA-GFN-Medium-Sequence"
run_name: "NM_018473-HomoSapiens-Protein"
device: "cuda"          






