_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
                - 100
                - 105
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
                - 100
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
device:
    value: auto
protein_seq:
    value: VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF
reward:
    value: mfe
run_name:
    value: mRNA-CondGFN
wandb_project:
    value: mRNA-Conditional-Sequence-design
